### ISSUE TITLE
Update find-my-way to version v2.0.1

### ISSUE THREAD

**Issue by mahovich** [Cweili/koa-router-find-my-way#1]
2 weeks ago updated version of find-my-way to [v2.0.1](https://github.com/delvedor/find-my-way/releases)
Probably worth updating it?

**Comment by Cweili** [comment]
Thanks, it's looks great.
You can use koa-router-find-my-way [v3.0.0](https://www.npmjs.com/package/koa-router-find-my-way/v/3.0.0) now.
