### ISSUE TITLE
Add support for [store] like fmw

### ISSUE THREAD

**Issue by wenq1** [Cweili/koa-router-find-my-way#27]
See #25.

**Comment by Cweili** [comment]
Nice work, thanks!

**Comment by Cweili** [comment]
[Simpler implementation](https://github.com/Cweili/koa-router-find-my-way/commit/c001a6ed23fec89b3f7e968184d2c959be969967).

Try new version v4.1.0

**Comment by wenq1** [comment]
I've also written jest test for that.

Are you sure store will be in ctx.store not in the last argument of the middleware?

As far as the doc is concerned (below), store is in the last argument. This is a bad idea as koa middlewares expect the signature to be (ctx, next), especially when you want to use compose ().

```
router.on('GET', '/example', (req, res, params, store) => {
  assert.equal(store, { message: 'hello world' })
}, { message: 'hello world' })
```

**Comment by wenq1** [comment]
I see. their doc is missing the fac tthat store is indeed in ctx.store...

**Comment by Cweili** [comment]
It matches koa middlewares and [passes your jest tests](https://travis-ci.com/github/Cweili/koa-router-find-my-way/builds/167581721).

Thanks for your contribution.
