### ISSUE TITLE
Add support for router search

### ISSUE THREAD

**Issue by mahovich** [Cweili/koa-router-find-my-way#3]
Add support for router lookup, as done by `find-my-way`:
```
find(method, path [, version])
```

[Documentation link](https://github.com/delvedor/find-my-way#findmethod-path--version).

**Comment by Cweili** [comment]
Thanks for the PR!

**Comment by Cweili** [comment]
I just release koa-router-find-my-way [v3.1.0](https://www.npmjs.com/package/koa-router-find-my-way/v/3.1.0).
